### ISSUE TITLE
Not able to record data

### ISSUE THREAD

**Issue by tgautam03** [kevinhughes27/TensorKart#64]
Hi 
I am trying to generate training data on another game and when I run record.py I get the following error.
```
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\Tushar\miniconda3\lib\tkinter\__init__.py", line 1705, in __call__
    return self.func(*args)
  File "record.py", line 162, in on_btn_record
    self.start_recording()
  File "record.py", line 207, in start_recording
    os.mkdir(self.outputDir)
OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect: 'C:/Users/Tushar/Desktop/github/TensorKart/samples/2020-05-16_13:53:22'
```

**Comment by bzier** [comment]
There are colons in the directory name, which aren't valid on Windows. You'll probably need to track down where the directory name is generated, based on the current date and time, and change the format to accommodate.

FYI, the development of this project was mostly done on Linux, so you may bump into other issues attempting to run this on Windows.
